version: '3'
services: 
   klevr-db:
      image: mariadb
      restart: always
#      volumes:
#         - ./data/mariadb:/var/lib/mysql
      environment:
         - MYSQL_ROOT_PASSWORD=root
      healthcheck:
         test: "/usr/bin/mysql --user=root --password=root --execute \"show databases;\""
         interval: 3s
         timeout: 1s
         retries: 10
      ports:
         - "3306:3306"

   klevr-manager:
      image: klevry/klevr-manager:latest
      ports: 
         - "8090:8090"
      depends_on: 
         - klevr-db
      links:
         - klevr-db
      command:
         - bash
         - -c
         - |
            chmod +x /init-db.sh
            /init-db.sh root root klevr-db 3306 klevr ./conf/klevr-manager-db.sql
            chmod +x /wait-for-it.sh
            /wait-for-it.sh klevr-db:3306 -t 10 -s -- echo "mariadb is up"
            /klevr-manager -c ./conf/klevr-manager-compose.yml
            
   nexclipper-server:
      image: mrchopa/nexclipper-server:latest
      ports:
         - "8080:8080"
      depends_on:
         - klevr-db
      links:
         - klevr-db
      environment:
         NC_REMOTE_KLEVR_INNER-URL: "http://192.168.8.51:8090"
         NC_REMOTE_KLEVR_OUTER-URL: "http://192.168.8.51:8090"
         NC_SECURITY_REPRESENTATION-DOMAIN: test.com
         SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT-URI: "http://test.com:8080/login/oauth2/code/{registrationId}"
      command:
         - bash
         - -c
         - |
            chmod +x /app/wait-for-it.sh
            /app/wait-for-it.sh klevr-db:3306 -t 10 -s -- echo "mariadb is up"
            chmod +x /app/init-db.sh
            /app/init-db.sh root root klevr-db 3306 nexclipper /app/conf/init.sql
            java -Dspring.profiles.active=compose -jar /app/*.jar