version: '3'
services:
   nexclipper-server:
      image: ${MODULE_IMAGE}
      container_name: dev_nexclipper-server
      ports:
         - "8080:8080"
      volumes:
         - ./db_backup:/nexclipper
      environment:
        NC_REMOTE_KLEVR_INNER-URL: "${KLEVR_INNER_URL}"
        NC_REMOTE_KLEVR_OUTER-URL: "${KLEVR_URL}"
        NC_KLEVR_COMMAND_AGENT-INSTALL: "curl -sL gg.gg/provbee | K3S_SET=N K_API_KEY=\"{API_KEY}\" K_PLATFORM=\"{PLATFORM}\" K_MANAGER_URL=\"{KLEVR_URL}\" K_ZONE_ID=\"{ZONE_ID}\" bash"
        NC_USERS_LOGIN_HANDLER_REDIRECT-URL: "${FRONT_URL}"
        NC_USERS_JWT_EXPIRATION: 3600
        NC_USERS_JWT_SECRET: "${JWT_SECRET}"
        NC_SECURITY_REPRESENTATION-DOMAIN: nexclipper.io
        NC_API_FRONT-REFRESH-INTERVAL: 5
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT-URI: "${NEXCLIPPER_URL}/login/oauth2/code/{registrationId}"
        SPRING_DATASOURCE_URL: "jdbc:mariadb://${NEXCLIPPER_DB_URL}:${NEXCLIPPER_DB_PORT}/nexclipper?useSSL=false&autoReconnect=true&characterEncoding=utf8"
        SPRING_DATASOURCE_USERNAME: "${NEXCLIPPER_DB_USER}"
        SPRING_DATASOURCE_PASSWORD: "${NEXCLIPPER_DB_PASSWD}"
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-ID: ${OAUTH_CLIENT_ID}
        SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT-SECRET: ${OAUTH_CLIENT_SECRET}
      command:
         - bash
         - -c
         - |
            /app/init-db.sh ${NEXCLIPPER_DB_USER} ${NEXCLIPPER_DB_PASSWD} ${NEXCLIPPER_DB_URL} ${NEXCLIPPER_DB_PORT} nexclipper /app/conf/init.sql /nexclipper
            java -Dspring.profiles.active=mvp1 -Dlogging.path=/nexclipper/log -jar /app/*.jar