logging:
  level:
    co.kr.nexcloud: debug
    co.kr.nexclipper: debug
#    org.thymeleaf: debug
    web: debug
    org.framework.security: debug
    co.kr.nexcloud.framework.jpa: info
    co.kr.nexclipper.nexclipperserver.remote.KlevrClient: debug

#server: 
#  http:
#    port: 80
#    host: 0.0.0.0

feign:
  client:
    config:
      default:
        loggerLevel: FULL
    
spring:
  jpa:
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
        format_sql: true